# Generated by Django 3.0.2 on 2020-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200403_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='altıncı',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='beşinci',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='dördüncü',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='üçüncü',
        ),
        migrations.AddField(
            model_name='choice',
            name='altinci',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='besinci',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='dorduncu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='ucuncu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='birinci',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='ikinci',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='imagename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='yedinci',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
